import { ReactNode } from "react";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Slack Clone",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"]
});

const RootLayout = ({children}: {children: ReactNode}) => {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          {children}
          <Toaster
            position="bottom-left"
            toastOptions={{
              style: {
                color: "white",
                backgroundColor: "#451c49"
              },
              duration: 5000
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;